### ISSUE TITLE
Can we get this updated for Foundry 12?

### ISSUE THREAD

**Issue by MisterCheesy** [lifer4700/13th-age-combat-loops#1]
See subject.  I'm getting yellow version warnings.

**Comment by lifer4700** [comment]
I'll take a look.   I doubt there will be a problem with v12, so hopefully it won't take long to check.

**Comment by lifer4700** [comment]
Verified for v12.

**Comment by MisterCheesy** [comment]
Thanks!  I think the only thing that has to be done is adjust the
manifest.  Id hate for it do disappear when foundry gets around to blocking
“old” extensions

**Comment by lifer4700** [comment]
I figured that out after I released 1.0.3
In 1.0.4 I actually changed the compatibility attribute in the module.json file.

**Comment by MisterCheesy** [comment]
Thanks you’re the best!
